import Head from "next/head";
import Hero from "./Hero";

export default function Home() {
  return (
    <div>
      <Head>
        <title>𝕹𝖊𝖜𝖘𝖑𝖊𝖙𝖙𝖊𝖗</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <Hero />
    </div>
  );
}
