import Head from "next/head";
import HomePage from "./home-page"

export default function Home() {
  return (
    <div>
      <Head>
        <title>Hero Curators</title>
        <link rel="shortcut icon" href="/assets/images/logo.png" />
        <meta name="description" content="Generated by create next app" />
      </Head>
      <HomePage/>
    </div>
  );
}
